
pool:
  vmImage: 'Ubuntu 16.04'

pr:
- master      

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: CmdLine@2
  inputs:
    script: 'pip install awscli'
- task: AWSCLI@1
  inputs:
    awsCredentials: 'AWS_Login'
    regionName: 'us-east-1'
    awsCommand: 'aws s3'
    awsSubCommand: 'ls'
  condition: always()
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.0'
  condition: always()

- task: Bash@3
  displayName: 'Terraform init'    
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      cd ./modules
      terraform init -backend-config='bucket=391501768339-redbox-tfstate' \
                     -backend-config='key=AzureDevops/terraform.tfstate'
  condition: always()

- task: GoTool@0
  inputs:
    version: '1.12.6'
  displayName: 'Set up the Go workspace'

- script: |
    ./scripts/install_ci.sh
  displayName: 'Set up Golang CI Tools'

- script: |
    make lint
  displayName: 'Run lint'    

- script: |
    ./scripts/test.sh
  displayName: 'Run Tests'

- task: PublishTestResults@2
  inputs:
    testRunner: JUnit
    testResultsFiles: $(System.DefaultWorkingDirectory)/junit-report/report.xml

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura 
    summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml

