pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  # Do not build branches
  branches:
    exclude:
      - "*"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master

variables:
  namespace: ${{ System.PullRequest.PullRequestNumber }}

steps:
  - script: |
      echo "PR: $(System.PullRequest.PullRequestNumber)"
      echo "Source branch: $(Build.SourceBranchName)"
      echo "Source branch name: $(Build.SourceBranchName)"
      echo "Namespace: $(namespace)"
    displayName: 'Test'
