pool:
  vmImage: 'Ubuntu 16.04'

trigger:
  # Do not build branches
  branches:
    exclude:
      - "*"
  # Run build on tagged versions
  tags:
    include:
      - "v*"

# Run builds for PRs against `master`
pr:
  - master

steps:
  - script: |



      echo "PR: $(System.PullRequest.PullRequestNumber)"
      echo "Source branch: $(Build.SourceBranchName)"
      echo "Source branch name: $(Build.SourceBranchName)"


      PR="$(System.PullRequest.PullRequestNumber)"
      BR="$(Build.SourceBranchName)"
      NS="${PR:-BR}"
      echo "$NS"

      echo "##vso[task.setvariable variable=NS]${NS}"

      echo "NS var: $(NS)"
    displayName: 'Test'
